name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'schema/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'schema/**'

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: ctype intl mbstring
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies
        run: |
          composer --version
          composer update --no-progress
      - name: Run PHP linter
        run: |
          find . -name \*.php  ! -path "./vendor/*" -exec php -l {} \;
      - name: Run unit tests
        run: |
          vendor/bin/phpunit -c tests/phpunit.xml.dist
